#!/bin/bash


LIBRE_PATH="$1" # full path to Libreelec
PATCHES="patches"

mkdir -p $PATCHES

if [ ! -d "$LIBRE_PATH" ];
then
  echo "LIBRE_PATH is wrong"
  exit 1
fi

cp -v $LIBRE_PATH/packages/multimedia/ffmpeg/patches/libreelec/*.patch $PATCHES
cp -v $LIBRE_PATH/packages/multimedia/ffmpeg/patches/v4l2-drmprime/*.patch $PATCHES
cp -v $LIBRE_PATH/packages/multimedia/ffmpeg/patches/v4l2-request/*.patch $PATCHES
cp -v $LIBRE_PATH/projects/Allwinner/patches/ffmpeg/*.patch $PATCHES


